---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: ./molecule/default/yaml-lint.yml
platforms:
  - name: instance
    box: ubuntu/trusty64
    groups: 
      - etcd_master 
    children:
      - addn_flag
provisioner:
  name: ansible
  options:
    vvv: True
  inventory:
    links:
#this is to test qa region
      group_vars: ../../../qa/group_vars
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
